<?php
define('USER_STATUS_WAITING_VALIDATE', 0);
define('USER_STATUS_VALIDATE', 1);

define('ROLE_LICENSEE', 1);
define('ROLE_CONTROLLER', 2);

return [
    'url_site' => array(
        'bonbanh' => 'http://www.bonbanh.com/',
        'muaban'  => 'https://muaban.net/',
        'chotot'  => 'https://xe.chotot.com/',
        'otovietnam'  => 'https://www.otovietnam.com/',
        'carmudi' => 'https://www.carmudi.vn/',
        'banxehoi' => 'http://banxehoi.com/',
        'choxe' => 'https://choxe.net/',
        'xe360' => 'http://xe360.vn/',
        'xe5giay' => 'https://www.5giay.vn/',
        'sanotovn' => 'http://sanotovietnam.com.vn/',
        'muabanoto' => 'http://www.muabanoto.vn/',
        'otos' => 'http://otos.vn/',
        'muabannhanh' => 'https://muabannhanh.com/',
        'rongbay' => 'http://rongbay.com/',
        'enbac' => 'http://oto.enbac.com/',
        'thegioixeoto' => 'http://thegioixeoto.com/',
        'otothien' => 'https://otothien.vn/',
        'cafeauto' => 'http://cafeauto.vn/',
    ),
    'brands' => array(
        '' => '--Thương hiệu--',
        'Acura' => 'Acura',
        'Aston Martin' => 'Aston Martin',
        'Audi' => 'Audi',
        'Bentley' => 'Bentley',
        'BMW' => 'BMW',
        'Buick' => 'Buick',
        'BYD' => 'BYD',
        'Cadillac' => 'Cadillac',
        'Chevrolet' => 'Chevrolet',
        'Chrysler' => 'Chrysler',
        'Citroen' => 'Citroen',
        'Daewoo' => 'Daewoo',
        'Dodge' => 'Dodge',
        'Ferrari' => 'Ferrari',
        'Fiat' => 'Fiat',
        'Ford' => 'Ford',
        'Geely' => 'Geely',
        'GMC' => 'GMC',
        'Haima' => 'Haima',
        'Honda' => 'Honda',
        'Hummer' => 'Hummer',
        'Hyundai' => 'Hyundai',
        'Infiniti' => 'Infiniti',
        'Isuzu' => 'Isuzu',
        'Jaguar' => 'Jaguar',
        'Jeep' => 'Jeep',
        'JRD' => 'JRD',
        'Kia' => 'Kia',
        'Lamborghini' => 'Lamborghini',
        'Land Rover' => 'Land Rover',
        'Land Rover' => 'Land Rover',
        'Lexus' => 'Lexus',
        'Lifan' => 'Lifan',
        'Luxgen' => 'Luxgen',
        'Maserati' => 'Maserati',
        'Maybach' => 'Maybach',
        'Mazda' => 'Mazda',
        'Mercedes' => 'Mercedes',
        'Mercury' => 'Mercury',
        'Merkur' => 'Merkur',
        'MINI' => 'MINI',
        'Mitsubishi' => 'Mitsubishi',
        'Nissan' => 'Nissan',
        'Peugeot' => 'Peugeot',
        'Plymouth' => 'Plymouth',
        'PMC' => 'PMC',
        'Porsche' => 'Porsche',
        'Ranger Rover' => 'Ranger Rover',
        'Renault' => 'Renault',
        'Rolls Royce' => 'Rolls Royce',
        'Saab' => 'Saab',
        'Saturn' => 'Saturn',
        'Scion' => 'Scion',
        'Smart' => 'Smart',
        'Ssangyong' => 'Ssangyong',
        'Steering' => 'Steering',
        'Subaru' => 'Subaru',
        'Suzuki' => 'Suzuki',
        'Tesla' => 'Tesla',
        'Toyota' => 'Toyota',
        'Volkswagen' => 'Volkswagen',
        'Volvo' => 'Volvo',
    )
];